stages:
  - build
  - test

job_build:
  tags:
    - docker-runner
  stage: build
  script:
    - echo "Build project"

job_test:
  tags:
    - docker-runner
  stage: test
  script:
    - echo "Running tests"