default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

variables:
  IMAGE_NAME: registry.barsikthecat.ru/$CI_PROJECT_PATH/bbx

before_script:
  - docker login -u "$CI_USER" -p "$DEPLOY_TOKEN" $REGISTRY

stages:
  - build
  - deploy

build_and_push_image:
  stage: build
  script:
    - CURRENT_DATE=$(date +%Y-%m-%d)
    - docker build -t $IMAGE_NAME-$CI_COMMIT_REF_NAME:$CURRENT_DATE-$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_NAME-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

deploy_to_production:
  stage: deploy
  script:
    - echo "commit $CI_COMMIT_SHORT_SHA"
  when: manual
  only:
    - main