name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    inputs:
       go-version:
         required: false
         type: string
         description: "Select the version of go to use"
         default: "^1.19.0"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}

    - name: Build
      run: go build ./sample.go

    - name: Run
      run: ./sample

    - name: Test
      run: go test -v ./...
