name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    inputs:
       go-version:
         required: true
         type: string
         description: "Select the version of go to use"
         default: "1.19.3"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}

    - name: Build
      run: go build ./sample.go

    - name: Run
      run: ./sample

    - name: Test
      run: go test -v ./...
